name: profitfolio

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: profitfolio_backend
    ports:
      - "8000:8000"
    volumes:
      - .:/workspace
      - ./sqlite_data:/data
    working_dir: /workspace/backend
    command: fastapi run app/main.py

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: profitfolio_frontend
    ports:
      - "3000:3000"
    volumes:
      - .:/workspace
      - /workspace/frontend/node_modules # 防止本機 node_modules 覆蓋容器的
    working_dir: /workspace/frontend
    command: npm run dev -- --host
